package org.bukkit;

public enum Material {
    AIR,
    LIGHT_BLUE_STAINED_GLASS,
    BLACK_CONCRETE,
    BLACKSTONE_BRICKS,
    POLISHED_BLACKSTONE_BRICKS,
    DEEPSLATE_TILES,
    GOLD_BLOCK,
    SEA_LANTERN,
    CHISELED_DEEPSLATE,
    POLISHED_BLACKSTONE,
    OBSIDIAN,
    POLISHED_BASALT,
    CUT_COPPER,
    WAXED_EXPOSED_COPPER,
    WAXED_WEATHERED_COPPER,
    SHROOMLIGHT,
    CHISELED_POLISHED_BLACKSTONE,
    LIGHTNING_ROD;
}
